### ISSUE TITLE
CRAN Checklist

### ISSUE THREAD

**Issue by brycefrank** [allometric/allometric#131]
- [x] Check that your package meets the [CRAN Repository Policy] and the [CRAN Package Submission Checklist].
- [x] Make sure your package has a DESCRIPTION file with the following fields: Package, Version, Date, Title, Author, Maintainer (with a valid email address), and License. You can use the [usethis::use_description()] function to create a template for this file.
- [x] Write a README file that explains the purpose and functionality of your package. You can use the [usethis::use_readme_rmd()] or [usethis::use_readme_md()] functions to create a template for this file.
- [x] Include a NAMESPACE file that specifies the exported and imported functions, methods, and classes of your package. You can use the [usethis::use_namespace()] function to create a template for this file.
- [x] Write documentation for every exported function, method, and class using [Roxygen2] syntax. You can use the [usethis::use_roxygen_md()] function to enable markdown support for Roxygen2.
- [x] Include at least one vignette that demonstrates how to use your package. You can use the [usethis::use_vignette()] function to create a template for this file.
- [x] Write unit tests for your package using [testthat]. You can use the [usethis::use_testthat()] function to set up the testing infrastructure and the [usethis::use_test()] function to create test files.
- [x] Run R CMD check on your package and fix any errors, warnings, or notes. You can use the [devtools::check()] or [rcmdcheck::rcmdcheck()] functions to run this check from R.
- [x] Build a source tarball of your package using R CMD build or [devtools::build()].
- [x] Upload your package to CRAN using R CMD submit or [devtools::submit_cran()]. You will need to provide an email address and a confirmation code that will be sent to you by CRAN.

**Comment by brycefrank** [comment]
Some more tasks specific to documentation cleaning

- [ ] Add slot docstrings to all S4 classes

**Comment by brycefrank** [comment]
Some policies we need to ensure are met:

- "Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory (or during installation in the location pointed to by TMPDIR: and such usage should be cleaned up). Installing into the system’s R installation (e.g., scripts to its bin directory) is not allowed.
Limited exceptions may be allowed in interactive sessions if the package obtains confirmation from the user."
   - I think we are technically ok here. The one thing to consider is adding a confirmation to `install_models`

**Comment by brycefrank** [comment]
Running into an issue with R CMD check. We are over the 5 mb limit. This is likely due to poor compression of the `model_1` and `model_2` `.rda` files used for the docstring examples. A cursory check reveals that `@predict_fn` and `@predict_fn_populated` are attached to the environment they were created in, which is saved along with the function. Hopefully there is a way to "remove" the environment from the function somehow. When replacing these two functions with dummy functions, the file size of the models goes from 850kb to 2kb

**Comment by brycefrank** [comment]
CRAN is erroring on install for Windows with the following:

```
* installing *source* package 'allometric' ...
ERROR: cannot remove earlier installation, is it in use?
* removing 'd:/RCompile/CRANincoming/R-devel/lib/allometric'
* restoring previous 'd:/RCompile/CRANincoming/R-devel/lib/allometric'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying d:\RCompile\CRANincoming\R-devel\lib\00LOCK-allometric\allometric\models\.git\objects\pack\pack-d54f7394ab329a3177007ad2a5f0735c269b1feb.idx to d:\RCompile\CRANincoming\R-devel\lib\allometric\models\.git\objects\pack\pack-d54f7394ab329a3177007ad2a5f0735c269b1feb.idx: Permission denied
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying d:\RCompile\CRANincoming\R-devel\lib\00LOCK-allometric\allometric\models\.git\objects\pack\pack-d54f7394ab329a3177007ad2a5f0735c269b1feb.pack to d:\RCompile\CRANincoming\R-devel\lib\allometric\models\.git\objects\pack\pack-d54f7394ab329a3177007ad2a5f0735c269b1feb.pack: Permission denied
```

I am not sure what step of the CRAN check this is, but it appears to be some issue with the file permissions in the .git directory of `models`. On CRAN, I want to avoid cloning `models` at all, so we should find why this is occurring and remove it.

**Comment by brycefrank** [comment]
Still having issues passing the CRAN automated checking. I have a suspicion that, somehow, `install_models` is running during the CRAN check. This downloads the `allometric/models` repository, which contains a `.git` directory, which causes issues when `R CMD INSTALL` copies the files from a temporary directory into the installation directory, because it does not have adequate permissions (apparently only on Windows, not Debian).

**Comment by brycefrank** [comment]
Passed auto check with v1.4.0!

**Comment by brycefrank** [comment]
Almost done. We have these tasks for resubmission 

Please always write package names, software names and API (application 
programming interface) names in single quotes in title and description.
e.g: --> 'allometric'
Please note that package names are case sensitive.

If there are references describing the methods in your package, please 
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for 
auto-linking. (If you want to add a title as well please put it in 
quotes: "Title")

Please add \value to .Rd files regarding exported methods and explain 
the functions results in the documentation. Please write about the 
structure of the output (class) and also what the output means. (If a 
function does not return a value, please document that too, e.g. 
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      check_local_models.Rd: \value
      get_variable_def.Rd: \value
      install_models.Rd: \value
      load_models.Rd: \value
      ParametricModel.Rd: \value
      ParametricSet.Rd: \value
      select_model.Rd: \value
      unnest_models.Rd: \value

**Comment by brycefrank** [comment]
v1.4.1 accepted today
